Sparse hessian with Symbolics.jl
JuliaSmoothOptimizers/ADNLPModels.jl pull request #126
Opened 2023-04-03 23:31 UTC by amontoison

2023-04-04 12:00 UTC, tmigot requested changes
Thanks @amontoison for the PR that looks great overall.

2023-04-04 12:00 UTC, tmigot commented on src/sparse_jacobian.jl
> +  nlp::ADModel,
Is there a reason to modify this?

2023-04-04 12:02 UTC, tmigot commented
Ok, so I didn't check the PR in the right order, some comments were valid for https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/125/files

2023-04-04 16:12 UTC, amontoison commented on src/sparse_hessian.jl
> +  S = Symbolics.hessian_sparsity(fun, ncon == 0 ? xsi : [xsi; ysi], full=false)
You have a `ncon == 0 ? xsi : [xsi; ysi]` and `ysi` is only used if it's defined.

2023-04-04 16:12 UTC, amontoison commented on src/sparse_jacobian.jl
> +  nlp::ADModel,
I just want to harmonize the functions.

2023-04-04 16:53 UTC, amontoison commented on src/sparse_hessian.jl
> +  y = zeros(T, nlp.meta.ncon)
Yes, we should also fix it in `NLPModelsJuMP.jl`.

2023-04-05 17:00 UTC, tmigot requested changes
I still have the `ysi` not defined error.

2023-04-05 17:00 UTC, tmigot commented on src/sparse_hessian.jl
> +  cfH = Symbolics.build_function(vals, xsi, ysi, μs, expression = Val{false})
but here `ysi` is not defined if `ncon = 0`.

2023-04-05 17:00 UTC, tmigot commented on src/sparse_hessian.jl
> +    ysi = Symbolics.scalarize(ys)
```suggestion
  @variables ys[1:ncon]
  ysi = Symbolics.scalarize(ys)
  if ncon > 0
```

2023-04-05 17:10 UTC, amontoison commented on src/sparse_hessian.jl
> +  cfH = Symbolics.build_function(vals, xsi, ysi, μs, expression = Val{false})
I don't understand why the tests passed :thinking:

2023-04-05 17:40 UTC, tmigot commented on src/sparse_hessian.jl
> +  y = zeros(T, nlp.meta.ncon)
I guess the fastest solution is to store `y` in the `SparseADHessian` structure.

2023-04-05 17:54 UTC, amontoison commented on src/sparse_hessian.jl
> +  y = zeros(T, nlp.meta.ncon)
Do you want that I update the PR or open a new one after this one?

2023-04-05 18:25 UTC, tmigot commented on src/sparse_hessian.jl
> +  y = zeros(T, nlp.meta.ncon)
Let's do another one.

2023-04-05 18:26 UTC, tmigot approved these changes
Thanks @amontoison  !!!! #13 #44 #106

2023-04-05 18:27 UTC, merged