Sparse hessian with SparseDiffTools.jl
JuliaSmoothOptimizers/ADNLPModels.jl pull request #127
Opened 2023-04-04 05:08 UTC by amontoison

@tmigot I have the wrong result when I use `autoauto_color_hessian!`.
I suspect an error in SparseDiffTools.jl. :thinking:

2023-04-07 19:56 UTC, dpo commented
Could we see a benchmark with JuMP just to know where this stands?

2023-04-07 21:26 UTC, amontoison commented
@tmigot Is it possible to do have a benchmark with the `SparseHessian` backend based on Symbolics.jl for Dominique?

2023-04-10 12:29 UTC, tmigot commented
The benchmark JuMP vs Symbolics Hessian:
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/benchmark/benchmark/2023-04-09_adnlpmodels_benchmark_hess_nscal_100_mono.png
for problems with about 100 variables and constraints.

2023-04-28 03:29 UTC, tmigot requested changes
Can you also change these two lines:
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/327bd6373be23901fbac2e87ec7cf142326699f0/src/ad.jl#L77

https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/327bd6373be23901fbac2e87ec7cf142326699f0/src/ad.jl#L108

to have this new backend by default?

2023-04-28 03:31 UTC, tmigot commented
![2023-04-27_adnlpmodels_benchmark_hess_nscal_1000_mono](https://user-images.githubusercontent.com/25304288/235047947-cb6e096a-6800-4773-8f94-7358fbd11dac.png)
Not bad!

2023-04-28 03:33 UTC, tmigot commented on src/sparse_hessian.jl
> +## ----- SparseDiffTools -----
Should we remove this comment?

2023-04-28 03:34 UTC, amontoison commented on src/sparse_hessian.jl
> +## ----- SparseDiffTools -----
Yes, I also propose the rename this backend `SparseADHessian`.

2023-04-28 03:43 UTC, tmigot requested changes

2023-04-28 03:43 UTC, tmigot commented on src/ad.jl
> +  hessian_backend::Type{HB} = ForwardDiffADHessian, # sparse alternative: SparseADHessian
```suggestion
  hessian_backend::Type{HB} = SparseADHessian,
```

2023-04-28 03:43 UTC, tmigot commented on src/ad.jl
> +  hessian_backend::Type{HB} = ForwardDiffADHessian, # sparse alternative: SparseADHessian
```suggestion
  hessian_backend::Type{HB} = SparseADHessian,
```

2023-04-28 03:45 UTC, amontoison commented
> Not bad! Sparse is this one, Forward is the dense ForwardDiff.
> 
> ![2023-04-27_adnlpmodels_benchmark_hess_nscal_1000_mono](https://user-images.githubusercontent.com/25304288/235047947-cb6e096a-6800-4773-8f94-7358fbd11dac.png)

Nice! Can you add the `Symbolic` version too?
We didn't optimize the directional derivative of the gradient this afternoon so it's already great!

2023-04-28 15:06 UTC, tmigot commented on src/sparse_hessian.jl
> +
The tests should pass after this:
```suggestion

function hess_coord!(
  b::SparseADHessian,
  nlp::ADModel,
  x::AbstractVector,
  j::Integer,
  vals::AbstractVector{T},
) where {T}
  y = zeros(T, nlp.meta.nnln)
  for (w, k) in enumerate(nlp.meta.nln)
    y[w] = k == j ? 1 : 0
  end
  obj_weight = zero(T)
  ℓ = get_lag(nlp, b, obj_weight, y)
  sparse_hess_coord!(ℓ, b, x, vals)
  return vals
end
```

2023-04-28 16:36 UTC, tmigot commented on src/sparse_hessian.jl
> +  ℓ(x) = obj_weight * nlp.f(x)
```suggestion
  ℓ = get_lag(nlp, b, obj_weight)
```
as `nlp.f` is not defined for NLS

2023-04-28 21:04 UTC, tmigot approved these changes
Looks good to me !
Next steps:
- [ ] improve hprod;
- [ ] add our own algo for thé coloration.

2023-04-28 21:18 UTC, merged

2023-04-29 06:29 UTC, jbcaillau commented
@amontoison @tmigot Hi guys, looks good: any release available for testing on sparse Jacobians / Hessians?

2023-04-29 16:07 UTC, amontoison commented
Hi @jbcaillau!
Tangi, do you think that we can do a release after #139?

2023-05-01 21:47 UTC, tmigot commented
Actually, we just need to try and solve https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/140 first, but next release should be in a week or 2. I will keep you guys updated when it is done.

2023-05-16 19:22 UTC, jbcaillau commented
@tmigot @amontoison hi there, any news on this? Actually, can you please update me on what might be pulled to test solving with sparse features?

2023-05-16 21:57 UTC, tmigot commented
Hi @jbcaillau ! ADNLPModels 0.6.2 has the sparse Hessian and Jacobian implemented. By the end of the month, there will be another upgraded version with improved `jprod`, `jtprod` and `hprod` and faster `Hessian/jacobian`.

2023-05-16 22:00 UTC, jbcaillau commented
Thanks @tmigot for the confirmation. I am forwarding to the ct team that they can rely on 0.6.2 to benchmark sparse derivatives 👍🏽

2023-05-31 06:31 UTC, amontoison commented
@jbcaillau 
We released [JuliaHSL](https://licences.stfc.ac.uk/product/julia-hsl) this week.
If you use Ipopt.jl, you will probably see a huge difference.

2023-05-31 07:02 UTC, jbcaillau commented
thanks @amontoison : does it require to apply for an academic license?

2023-05-31 12:15 UTC, amontoison commented
Yes, you need to apply for an academic license.

2023-05-31 20:48 UTC, jbcaillau commented
✅ order passed 🤞🏾

2023-07-14 12:59 UTC, jbcaillau commented
Hi @tmigot @amontoison! Not sure to be on the right issue, but anyway: as JuliaCon approaches, we are on the way to announce the last release of [control-toolbox](https://control-toolbox.org). Any news of performance increase for sparse Hessians?

2023-07-14 17:11 UTC, tmigot commented
Hi @jbcaillau ! I will make a last attempt on Monday to extend to the Lagrangian what we did there https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/171 . I keep you updated.