Optimize hprod in sparse hessian
JuliaSmoothOptimizers/ADNLPModels.jl pull request #167
Opened 2023-06-22 15:49 UTC by tmigot

@amontoison This is not ideal for the objective Hessian, and I have done it quickly, but it should work :).

2023-06-22 16:59 UTC, amontoison requested changes

2023-06-22 16:59 UTC, amontoison commented on src/sparse_hessian.jl
> +  b.sol[(ncon + nvar + 1):(2 * ncon + nvar)] .= y
```suggestion
  view(b.sol, 1:ncon) .= zero(T) # cx
  view(b.sol, (ncon + 1):(ncon + nvar)) .= x
  view(b.sol, (ncon + nvar + 1):(2 * ncon + nvar)) .= y
```

2023-06-22 17:00 UTC, amontoison commented
It is still slow compared to JuMP :(
```julia
julia> include("bench.jl")
Hessian of Lagrangian
ADNLP
  3.635 ms (4370 allocations: 8.58 MiB)
JuMP
  58.046 μs (137 allocations: 24.08 KiB)
Jacobian of constraints
ADNLP
  10.219 μs (22 allocations: 20.75 KiB)
JuMP
  14.944 μs (15 allocations: 19.80 KiB)
```

2023-06-23 05:58 UTC, tmigot commented on src/sparse_hessian.jl
> +  b.sol[(ncon + nvar + 1):(2 * ncon + nvar)] .= y
I have tested this, and it does not change the allocations.
```
using ADNLPModels, NLPModels; f(x) = sum(x); nlp = ADNLPModel(f, ones(2)); hess(nlp, nlp.meta.x0, nlp.meta.y0); @allocated hess(nlp, nlp.meta.x0, nlp.meta.y0)
```

2023-06-23 05:58 UTC, tmigot commented on src/sparse_hessian.jl
> +    b.longv[(ncon + 1):(ncon + nvar)] .= b.d
same as above

2023-06-23 06:01 UTC, tmigot commented
> It is still slow compared to JuMP :(
> 
> ```julia
> julia> include("bench.jl")
> Hessian of Lagrangian
> ADNLP
>   3.635 ms (4370 allocations: 8.58 MiB)
> JuMP
>   58.046 μs (137 allocations: 24.08 KiB)
> Jacobian of constraints
> ADNLP
>   10.219 μs (22 allocations: 20.75 KiB)
> JuMP
>   14.944 μs (15 allocations: 19.80 KiB)
> ```

Can you check that you used the right branch for this test? Because, the allocation result is exactly the same as https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/issues/165#issuecomment-1599374463

Will https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/166 bring any improvement?

2023-06-26 01:27 UTC, dpo commented on src/sparse_hessian.jl
> +  b.sol[(ncon + nvar + 1):(2 * ncon + nvar)] .= y
On the left-hand side, a view is always used I believe.

2023-06-27 21:18 UTC, amontoison commented on src/sparse_hessian.jl
> +  y = zeros(eltype(x), nlp.meta.nnln)
Is it possible to preallocate this vector?

2023-06-28 18:26 UTC, amontoison approved these changes

2023-06-28 18:27 UTC, merged