Parametric NLPModelMeta
JuliaSmoothOptimizers/ADNLPModels.jl pull request #20
Opened 2021-06-11 19:31 UTC by tmigot

Follows [NLPModels.jl PR #353](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/353) with parametric meta.

2021-06-11 19:43 UTC, abelsiqueira requested changes

2021-06-11 19:43 UTC, abelsiqueira commented on src/nlp.jl
It should be `ADNLPModel(f, x0::S; ...)` and `T = eltype(S)`. Unless we can't have other types of `S` for AD

2021-06-12 18:10 UTC, abelsiqueira commented on src/nlp.jl
>    uvar::AbstractVector;
```suggestion
  lvar::S,
  uvar::S;
```
What do think?

2021-06-13 18:06 UTC, tmigot commented on src/nlp.jl
>    uvar::AbstractVector;
It looks ok, because this is a constraint in the meta. I just thought it would be more general, in case we modify (again) de types in the meta.

2021-06-13 18:10 UTC, dpo commented on src/nlp.jl
>    uvar::AbstractVector;
Abstract types inside structs break type inference.

2021-06-13 18:12 UTC, tmigot commented on src/nlp.jl
>    uvar::AbstractVector;
Yes, but this suggestion was in the inputs of the constructor.

2021-06-13 18:16 UTC, dpo commented on src/nlp.jl
>    uvar::AbstractVector;
Ah I see, sorry. But how does it work if not all vectors have the same "type"? You have to perform conversions?

2021-06-13 18:19 UTC, tmigot commented on src/nlp.jl
>    uvar::AbstractVector;
Right now, if `lvar` has a different type, the error will come from the `NLPModelMeta` constructor instead of the `ADNLPModels` constructor.
My point was just anticipating cases where `lvar` would have a different type than `x0`, e.g. sparse vector. But, it is probably anticipating too much. So, I will update.

2021-06-17 16:36 UTC, abelsiqueira approved these changes

2021-06-17 16:37 UTC, abelsiqueira commented
Thanks

2021-06-17 16:37 UTC, merged