Add tutorial with manual sparsity pattern
JuliaSmoothOptimizers/ADNLPModels.jl pull request #209
Opened 2023-12-21 19:34 UTC by tmigot

2023-12-22 11:50 UTC, tmigot commented
This is a tuto on adding manually the sparsity pattern, but not the results expected tbh...

2024-08-06 20:50 UTC, tmigot commented
superseded by #286

2024-08-13 02:53 UTC, amontoison requested changes

2024-08-13 02:53 UTC, amontoison commented on docs/make.jl
> +    "Fine-tune sparse derivatives" => "sparsepattern.md",
```suggestion
    "Provide sparsity pattern for sparse derivatives" => "sparsity_pattern.md",
```

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +In this tutorial, we show a simple trick to potentially improve the computation of sparse Jacobian and Hessian matrices.
```suggestion
In this tutorial, we show a feature of ADNLPModels.jl to potentially improve the computation of sparse Jacobian and Hessian.
```

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +`ADNLPModel` will automatically try to prepare AD-backend to compute sparse Jacobian and Hessian.
```suggestion
`ADNLPModel` will automatically prepare an AD backend for computing sparse Jacobian and Hessian.
```

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +The keyword argument `show_time = true` can also be passed to the problem's constructor to get more detailed information about the time used to prepare the AD backend.
On devrait s'en servir pour isoler le calcul du sparsity pattern / coloring / preparation AD / AD / decompression.
Peut-être ouvrir une issue?

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +However, it can be rather costly to determine for a given function the sparsity pattern of the Jacobian and the Lagrangian Hessian matrices.
```suggestion
However, it can be rather costly to determine for a given function the sparsity pattern of the Jacobian and the Hessian of the Lagrangian.
```

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +The good news is that it can be quite easy to have a good approximation of this pattern dealing with problems like our optimal control investment problem, and problem with differential equations in t
```suggestion
The good news is that determining this pattern a priori can be relatively straightforward, especially for problems like our optimal control investment problem and other problems with differential equations in the constraints.
```

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +  J = spzeros(Bool, N - 1, n)
Il faut que tu fasses `colptr`, `rowval`, `nzval` toi même et qu'ensuite tu utilises le constructeur `SparseMatrixCSC`.
Tu fais nnz allocations dynamique avec à chaque fois un check si le nnz existe déjà.
Ça ne peut être que lent :smiley:

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +The same can be done for the Lagrangian Hessian.
```suggestion
The same can be done for the Hessian of the Lagrangian.
```

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +A similar Jacobian matrix is obtained potentially at a lower price.
```suggestion
We recover the same Jacobian.
```

2024-08-13 02:53 UTC, amontoison commented on docs/src/sparsepattern.md
> +A similar Jacobian matrix is obtained potentially at a lower price.
C'est pas vraiment à plus bas prix vu que c'est que de la différentiation automatique pour calculer le jacobien.
C'est vraiment sur le "setup" du backend qu'on gagne.

2024-08-13 11:44 UTC, tmigot commented on docs/src/sparsepattern.md
> +The keyword argument `show_time = true` can also be passed to the problem's constructor to get more detailed information about the time used to prepare the AD backend.
Bonne idée!

2024-08-14 21:45 UTC, merged