Upgrade ADNLPModels.jl for SparseMatrixColoring.jl v0.4.0
JuliaSmoothOptimizers/ADNLPModels.jl pull request #289
Opened 2024-08-13 16:54 UTC by amontoison

cc @gdalle

2024-08-13 18:16 UTC, gdalle requested changes

2024-08-13 18:16 UTC, gdalle commented on src/sparse_hessian.jl
> +  star_set = result.star_set
the `star_set` is no longer part of the public API, you have to rely on `decompress` instead

2024-08-13 18:16 UTC, gdalle commented on src/sparse_hessian.jl
> +  star_set = result.star_set
same remark here about the `star_set`

2024-08-13 18:30 UTC, amontoison commented on src/sparse_hessian.jl
> +  star_set = result.star_set
I don't want to always store all the compressed columns if I use direct recovery.
It could be prohibitive in terms of storage.
I just want to use `decompress` for the acyclic coloring and use star coloring as a backup if memory becomes an issue.
Also `decompress` don't support an option to update just one triangle right now, which is important for me.

2024-08-15 05:24 UTC, gdalle requested changes

2024-08-15 05:24 UTC, gdalle commented on docs/src/sparse.md
> +The default algorithm is `GreedyColoringAlgorithm{:direct}()` from the package `SparseMatrixColorings.jl`.
Not worth specifying that it must subtype `ADTypes.AbstractColoringAlgorithm`, because the one from SparseMatrixColorings is the only subtype we support. Better to say that it must be an instance of `SparseMatrixColorings.GreedyColoringAlgorithm`

2024-08-15 05:24 UTC, gdalle commented on docs/src/sparse.md
> +The available backends for sparse derivatives (`SparseADJacobian`, `SparseADHessian` and `SparseReverseADHessian`) have keyword arguments `detector` and `coloring_options` to specify the sparsity pat
Why not name it `coloring_algorithm`?

2024-08-15 05:24 UTC, gdalle commented on src/sparse_hessian.jl
> +  for (icol, cols) in enumerate(groups)
Why is `A` not used with `decompress!` in this loop?

2024-08-15 19:15 UTC, gdalle commented on docs/src/sparse.md
> +The default algorithm is `GreedyColoringAlgorithm{:direct}()` from the package `SparseMatrixColorings.jl`.
@amontoison this is important

2024-08-15 22:59 UTC, amontoison commented on docs/src/sparse.md
> +The default algorithm is `GreedyColoringAlgorithm{:direct}()` from the package `SparseMatrixColorings.jl`.
Done

2024-08-15 23:37 UTC, merged