Add a function get_sparsity_pattern
JuliaSmoothOptimizers/ADNLPModels.jl pull request #307
Opened 2024-11-25 22:37 UTC by amontoison

close #300
@frapac @sshin23 @jbcaillau @tmigot 

I added a function, `get_sparsity_pattern`, to easily extract the sparsity pattern of the Jacobian or the Hessian of the Lagrangian from any `ADNLPModel` or `ADNLSModel`.  
This could help detect specific patterns that can be exploited in the linear algebra computations.  
Additionally, if a problem needs to be solved multiple times, we can skip the sparsity pattern detection step by directly injecting the previously extracted pattern.

Example: https://jso.dev/ADNLPModels.jl/dev/sparsity_pattern/

2024-11-25 22:56 UTC, tmigot requested changes
Thanks for the PR @amontoison !
Here is a first batch of comments.

2024-11-25 22:56 UTC, tmigot commented on docs/src/sparse.md
> +```
```suggestion
`ADNLPModels.jl` provides the function [`get_sparsity_pattern`](@ref) to retrieve the sparsity patterns of the Jacobian or Hessian from a model.
```

2024-11-25 22:56 UTC, tmigot commented on docs/src/sparse.md
> +H = get_sparsity_pattern(nlp, :hessian)
Maybe put this in a separate block code?

2024-11-25 22:56 UTC, tmigot commented on docs/src/sparse.md
> +H = SparseMatrixCSC{Bool,Int}(
```suggestion
H = SparseMatrixCSC{Bool, Int}(
```

2024-11-25 22:56 UTC, tmigot commented on docs/src/sparse.md
> +J = SparseMatrixCSC{Bool,Int}(
```suggestion
J = SparseMatrixCSC{Bool, Int}(
```

2024-11-25 22:56 UTC, tmigot commented on docs/src/sparse.md
> +
```suggestion
```

2024-11-25 22:56 UTC, tmigot commented on src/sparsity_pattern.jl
> +function get_sparsity_pattern(model::ADModel, derivate::Symbol)
I think it would be better design to do:
`get_sparsity_pattern(model::ADModel, derivate::Symbol) = get_sparsity_pattern(model, Val(derivative))`
and then define
- `get_sparsity_pattern(model::ADModel, Union{Val{:jacobian}, Val{:jacobian_residual}})`
- `get_sparsity_pattern(model::ADModel, Union{Val{:hessian}, Val{hessian_residual}))`
thus allowing dispatch.

2024-11-25 22:56 UTC, tmigot commented on src/sparsity_pattern.jl
> +    elseif (derivate != :jacobian_residual) && (derivate != :hessian_resiual)
```suggestion
    elseif  (model isa AbstractADNLSModel) && (derivate != :jacobian_residual) && (derivate != :hessian_resiual)
    # ...
    else
    # ERROR
```

2024-11-25 23:01 UTC, amontoison commented on src/sparsity_pattern.jl
> +function get_sparsity_pattern(model::ADModel, derivate::Symbol)
Good idea!
I didn't remember that we can do that with `Val`

2024-11-26 00:49 UTC, amontoison commented on src/sparsity_pattern.jl
> +function get_sparsity_pattern(model::ADModel, derivate::Symbol)
Done :+1:

2024-11-26 00:53 UTC, amontoison commented on docs/src/sparse.md
> +H = get_sparsity_pattern(nlp, :hessian)
Good suggestion Tangi :smiley:

2024-11-26 22:30 UTC, tmigot approved these changes
I just made a cosmetic comment, otherwise it's good to me. Thanks!

2024-11-26 22:30 UTC, tmigot commented on src/sparsity_pattern.jl
> +end
```suggestion
function validate_sparse_backend(backend::B, expected_type, derivative_name::String) where {B <: ADBackend}
    if !(backend isa expected_type)
        error("The current backend $B doesn't compute a sparse $derivative_name.")
    end
end
```

2024-11-26 23:16 UTC, amontoison commented on src/sparsity_pattern.jl
> +end
Why do want to specialize this method for the backend?

2024-11-26 23:18 UTC, amontoison commented on src/sparsity_pattern.jl
> +end
Oh I see, you suggest that to already have the type for the error.
We overspecialize this method but that's fine. It's a cheap one.

2024-11-26 23:19 UTC, amontoison commented
Thanks for the review @tmigot 👍

2024-11-27 00:19 UTC, merged