Allow use of Zygote or ReverseDiff
JuliaSmoothOptimizers/ADNLPModels.jl pull request #4
Opened 2021-03-20 17:18 UTC by mohamed82008

This PR enables the use of Zygote or ReverseDiff in ADNLPModel using Requires.jl to avoid depending on either. Reverse-mode AD would unlock the true power of the augmented Lagrangian algorithm in Percival.jl since it avoids the computation of the whole Jacobian.

2021-03-20 18:28 UTC, dpo commented
Thanks! I think that’s a great idea. Do you think it would be possible to also enable ModelingToolkit like this (not necessarily in this PR)?

2021-03-20 18:29 UTC, mohamed82008 commented
>Do you think it would be possible to also enable ModelingToolkit like this (not necessarily in this PR)?

What do you mean by enable MTK?

2021-03-20 18:31 UTC, mohamed82008 commented
Ah for symbolic AD. Yes it would be possible.

2021-03-20 18:31 UTC, dpo commented
I mean to compute derivatives.

2021-03-20 18:32 UTC, mohamed82008 commented
We were a second apart!

2021-03-20 18:44 UTC, abelsiqueira requested changes
Thanks, this is a great improvement. I haven't looked into the details of `ad.jl` but overall it looks good. I have a few more comments below:

You also need to add these tests to `nl{p,s}/nlpmodelstest.jl`, which is where the consistency checks are made.

I liked the idea of using struct for the AD backends - kind of like traits. I am wondering though if it makes sense to make `ADNLPModel` parametric and have the type be the AD backend. This could help if some API function can be specialized, though I'm not sure it that's necessary.

Finally, I'll let @amontoison and @tmigot take a look, because they are implementing a new sparse AD model too.

2021-03-20 18:44 UTC, abelsiqueira commented on Project.toml
> +test = ["NLPModelsModifiers", "NLPModelsTest", "Test", "Zygote", "ReverseDiff"]
Can you add these sorted?

2021-03-20 18:44 UTC, abelsiqueira commented on test/nls/basic.jl
> +    @testset "autodiff_nls_test" begin
```suggestion
    @testset "autodiff_nls_test for $adbackend" begin
```

2021-03-20 18:44 UTC, abelsiqueira commented on README.md
> -It uses [`ForwardDiff`](https://github.com/JuliaDiff/ForwardDiff.jl) to compute the derivatives, which produces dense matrices, so it isn't very efficient for larger problems.
We should probably add a few lines on the available options for AD.

2021-03-20 18:46 UTC, mohamed82008 commented on Project.toml
> +test = ["NLPModelsModifiers", "NLPModelsTest", "Test", "Zygote", "ReverseDiff"]
Sure

2021-03-21 16:57 UTC, mohamed82008 commented
I removed the Zygote nls models tests because some of these models had mutation and Zygote doesn't support mutation. I think the only failing inverse dependency tests are those of QuadraticModels.jl because of Requires. https://github.com/JuliaSmoothOptimizers/QuadraticModels.jl/pull/35 should fix it.

2021-03-21 17:16 UTC, mohamed82008 commented
The tests seem to pass now. This is ready for another review.

2021-03-21 23:08 UTC, abelsiqueira requested changes
Took some more time because I was testing the modifications I proposed.
By the way, when I merge this I intend to squash the commits to keep the history concise. Do you prefer to rearrange and squash them in some other way?

2021-03-21 23:08 UTC, abelsiqueira commented on src/nls.jl
> +  return tril(jacobian(nls.adbackend, x -> pullback(nls.adbackend, nls.F, x, v), x))
You mentioned that `ZygoteAD` fails on the consistency checks, so you removed it. It looks like it's because of this line and the other `hess_coord_residual` below. I changed to the following:
```suggestion
  ϕ(x) = dot(nls.F(x), v)
  return tril(hessian(nls.adbackend, ϕ, x))
```
as similarly to `hess_coord_residual`.
I don't know enough about ADs to know if this breaks something else.

2021-03-21 23:36 UTC, mohamed82008 commented
>By the way, when I merge this I intend to squash the commits to keep the history concise. Do you prefer to rearrange and squash them in some other way?

Ya feel free to squash.

2021-03-21 23:49 UTC, mohamed82008 commented on src/nls.jl
> +  return tril(jacobian(nls.adbackend, x -> pullback(nls.adbackend, nls.F, x, v), x))
ya this was it, thanks!

2021-03-22 00:21 UTC, mohamed82008 commented
Tests seem to be passing.

2021-03-22 01:39 UTC, tmigot approved these changes
Added some comments, but overall I think it is great!

Using `Require.jl` is a neat way of not adding tons of dependencies. However, the drawback is that we have no compatibility control with these packages. Any suggestions for that?

2021-03-22 01:39 UTC, tmigot commented on test/runtests.jl
> +  ADNLPModel(nlp.meta, nlp.counters, adbackend, nlp.f, nlp.c)
Since `ADNLPModel` is a mutable struct, couldn't we do `nlp.adbackend = adbackend`? (same for nls)

2021-03-22 01:39 UTC, tmigot commented on src/ad.jl
> +gradient(b::ADBackend, ::Any, ::Any) = throw_error(b)
Maybe, we are now probably missing `@test_throws` type tests for these errors.

2021-03-22 02:03 UTC, tmigot commented
I am personally not a huge fan of `pushforward` and `pullback` as it is not clear they are related to the jacobian. Besides, functions like `pullback` are also used in Zygote to compute the gradient. For instance, what about using `∇c` and `∇ct`?

@amontoison We could very simply fit in this new framework by adding attributes in the `ADBackend` structures with specialized constructors.

2021-03-22 05:58 UTC, mohamed82008 commented
>I am personally not a huge fan of pushforward and pullback as it is not clear they are related to the jacobian. Besides, functions like pullback are also used in Zygote to compute the gradient. For instance, what about using ∇c and ∇ct?

These are terms from the autodiff world (https://juliadiff.org/ChainRulesCore.jl/stable/#The-propagators:-pushforward-and-pullback). Zygote is the one confusing everyone actually because it uses the term in a different way to return the function output and the pullback function rather than performing the pullback operation. I can rename them to `Jprod` and `Jtprod` if you prefer those.

>Using Require.jl is a neat way of not adding tons of dependencies. However, the drawback is that we have no compatibility control with these packages. Any suggestions for that?

You can have more packages in the compat section than the main dependencies I think. But the API of these packages has been stable for a while so I suspect we need to do much in that regard.

2021-03-22 13:51 UTC, dpo commented
Let's use Jprod and Jtprod since that's closer to the optimization nomenclature. Let's also make sure anything that could be `Require`d is tested in the unit tests.

2021-04-02 07:29 UTC, mohamed82008 commented
Sorry for the late response. I addressed all the comments.

2021-04-02 10:07 UTC, dpo requested changes
Looks amazing, many thanks!!! Just a couple of comments.

2021-04-02 10:07 UTC, dpo commented on Project.toml
> +ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Will this always test the latest release? Is there a way to set versions here?

2021-04-02 10:19 UTC, mohamed82008 commented on Project.toml
> +ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
It will use the latest release. I don't recommend setting bounds on optional dependencies. It's possible though.

2021-04-05 11:42 UTC, abelsiqueira commented
There's some violent error on Cirrus CI on 1.6:
```
ERROR: Package ADNLPModels errored during testing (received signal: KILL)
```
A similar one in 1.3, with the signal information. They happen in different places.
@dpo, any suggestions? Remove Cirrus CI?

2021-04-05 11:46 UTC, abelsiqueira commented on Project.toml
> +ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
> I don't recommend setting bounds on optional dependencies.

Can you expand on this? I am hoping CompatHelper will update them.

2021-04-05 12:54 UTC, dpo commented
They happen in the same place: Julia hangs in the constructors for NLS tests. The question is why.

2021-04-05 13:25 UTC, abelsiqueira commented
I don't think so, they start after `nls/basic.jl` is run, and inside the NLP consistency.

On [1.3](https://cirrus-ci.com/task/5932749627326464?logs=test#L36), it errors inside the first backend, but on [1.6](https://cirrus-ci.com/task/5574802019713024?logs=test#L94), it errors inside the second backend. Unfortunately, there is no information on where.

2021-04-05 23:11 UTC, mohamed82008 commented on Project.toml
> +ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
It's just unnecessary bounds. These bounds can create conflicts just because a package exists even if the user doesn't need to load it with ADNLPModels.

2021-04-05 23:13 UTC, abelsiqueira commented on Project.toml
> +ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Makes sense.

2021-04-06 16:51 UTC, dpo commented
Could you please rebase, so we can verify that the unit tests pass on FreeBSD?

2021-04-06 17:39 UTC, dpo commented
Hmm. I wonder what the difference is between this PR and #7. Here, Julia nightly gets killed on FreeBSD (signal 11).

2021-04-06 17:43 UTC, dpo approved these changes

2021-04-06 18:31 UTC, merged

2021-04-06 18:31 UTC, abelsiqueira commented
Thanks